# Install Redis.

# # yum install epel-release yum-utils -y
# # yum install http://rpms.remirepo.net/enterprise/remi-release-7.rpm -y
# # yum-config-manager --enable remi
# # yum install redis -y
# Update the BindIP from 127.0.0.1 to 0.0.0.0 in config file /etc/redis.conf & /etc/redis/redis.conf

# Start Redis Database


# # systemctl enable redis
# # systemctl start redis

- name: Install Redis Repos
  yum:
    name: http://rpms.remirepo.net/enterprise/remi-release-9.rpm
    state: present

- name: Enable Redis repo and install Redis
  yum:
    name: redis
    enablerepo: remi
    state: present

- name: Update IP in redis.conf
  ansible.builtin.replace:
    path: /etc/redis/redis.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

- name: Restart and enable redis service
  systemd:
    name: redis
    state: restarted
    enabled: yes

