- name: Setup MongoDB Repo
  ansible.builtin.copy:
   src: mongodb.repo
   dest: /etc/yum.repos.d/mongodb.repo

- name: Install MongoDB
  yum:
   name: mongodb-org
   state: present

- name: Update IP in mongod.conf
  ansible.builtin.replace:
    path: /etc/mongod.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

- name: Restart MongoDB service
  systemd:
   name: mongod
   state: restarted
   enabled: yes

- name: Download and Unzip MongoDB Schema
  ansible.builtin.unarchive:
   src: https://github.com/roboshop-devops-project/mongodb/archive/main.zip
   dest: /tmp
   remote_src: yes

# - name: Load Schema for Catalogue
#   community.mongodb.mongodb_shell:
#     file: "/tmp/mongodb-main/catalogue.js"
#     idempotent: yes

- name: Load Schema for Users
  community.mongodb.mongodb_shell:
    file: "/tmp/mongodb-main/users.js"
    idempotent: yes
