- name: Install Python36, gcc and python3-devel
  yum:
   name:
    - python3
    - gcc
    - python3-devel
   state: present

- name: Include common role
  include_role:
   name: common
   tasks_from: download.yaml

- name: Install specified python requirements
  ansible.builtin.pip:
    requirements: /home/roboshop/{{COMPONENT}}/requirements.txt
    executable: pip3 

- name: Print Roboshop User
  debug:
   msg: "{{ROBOSHOP_USER}}"

- name: Update roboshop user id
  ansible.builtin.lineinfile:
    path: /home/roboshop/{{COMPONENT}}/{{COMPONENT}}.ini
    regexp: '^uid'
    line: uid = {{ROBOSHOP_USER.uid}}

- name: Update roboshop group id
  ansible.builtin.lineinfile:
    path: /home/roboshop/{{COMPONENT}}/{{COMPONENT}}.ini
    regexp: '^gid'
    line: gid = {{ROBOSHOP_USER.group}}

- name: Include Common role for Systemd task
  include_role:
   name: common
   tasks_from: systemd

- name: Include common role for node_exporter installation
  include_role:
   name: common
   tasks_from: node_exporter.yaml