- name: Install Nginx
  yum:
    name:  nginx
    state: present

- name: Unzip archive for frontend
  ansible.builtin.unarchive:
    src: https://github.com/roboshop-devops-project/frontend/archive/main.zip
    dest: /tmp
    remote_src: yes

- name: Remove Old Content from html directory
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: absent

- name: Copy Static directory
  ansible.builtin.copy:
    src: /tmp/frontend-main/static/
    dest: /usr/share/nginx/html/
    remote_src: yes

- name: Move localhost.conf to frontend machine
  ansible.builtin.copy:
    src: roboshop.conf
    dest: /etc/nginx/default.d/roboshop.conf
  notify: Restart Nginx

- name: Start and enable Nginx
  systemd:
    name: nginx
    state: started
    enabled: yes

- name: Include common role for node_exporter installation
  include_role:
   name: common
   tasks_from: node_exporter