- name: Copy mysql.repo file to "/etc/yum.repos.d/mysql.repo" to setup repo
  ansible.builtin.copy:
   src: mysql.repo
   dest: /etc/yum.repos.d/mysql.repo

- name: Remove mariadb-libs
  yum:
   name: mariadb-libs
   state: absent

- name: Install MySql
  yum:
   name: 
    - mysql-server
   state: present
  pip:
    name: pymysql
    state: present
    
- name: Start and enable MySqld service
  systemd:
   name: mysqld
   state: restarted
   enabled: yes

- name: Check the Password reset status
  shell: echo 'show databases' | mysql -uroot -pRoboShop@1
  register: out
  ignore_errors: yes
  # debug:
  #  msg: "{{out}}"

- name: Grab default Password
  shell: grep 'A temporary password' /var/log/mysql/mysqld.log | awk '{print $NF}'
  register: default_pass
  when: out.rc != 0

- name: Reset SQL file
  copy:
    src: reset.sql
    dest: /tmp/reset.sql
  when: out.rc != 0


- name: Reset MySQL Password
  shell: "mysql -u root -p'{{default_pass.stdout}}' </tmp/reset.sql"
  when: out.rc != 0


- name: Check Password Validate Plugin
  shell: echo 'show plugins;' | mysql -u root -p"RoboShop@1" 2>/dev/null | grep -i validate_password
  register: val_out
  ignore_errors: yes

- name: Uninstall Password Validate Plugin
  shell: echo "uninstall plugin validate_password;" >/tmp/pass.sql ; mysql -u root -p"RoboShop@1" </tmp/pass.sql
  when: val_out.rc == 0

- name: Download MySQL Schema
  ansible.builtin.unarchive:
    src: "https://github.com/roboshop-devops-project/mysql/archive/main.zip"
    dest: /tmp
    remote_src: yes

- name: Load Schema
  mysql_db:
    state: import
    name: all
    target: /tmp/mysql-main/shipping.sql
    login_password: RoboShop@1
    login_user: root

