- name: Install NodeJS, Make and GCC
  yum:
   name:
    - nodejs
    - make
    - gcc-c++
   state: present

- name: Add Roboshop user
  ansible.builtin.user:
    name: roboshop

- name: Download and unzip Catalogue Archive
  ansible.builtin.unarchive:
    src: https://github.com/roboshop-devops-project/catalogue/archive/main.zip
    dest: /tmp
    remote_src: yes

- name: Remove old content from catalogue directory
  ansible.builtin.file:
    path: /home/roboshop/catalogue
    state: absent

- name: Copy extracted content to catalogue directory
  ansible.builtin.copy:
   src: /tmp/catalogue-main/
   dest: /home/roboshop/catalogue/
   remote_src: yes
   owner: roboshop
   group: roboshop

- name: Install NodeJs dependencies
  community.general.npm:
    path: /home/roboshop/catalogue
  become_user: roboshop

- name: Copy Systemd service file of catalogue to setup service
  ansible.builtin.copy:
    src: systemd.service
    dest: /etc/systemd/system/catalogue.service

- name: Restart catalogue service
  systemd:
    name: catalogue
    state: restarted
    daemon_reload: true
    enabled: yes
