- name: UPDATE or Copy prometheus.yml to prometheus directory
  template:
   src: "{{item}}.yml"
   dest: /opt/prometheus/{{item}}.yml
  loop:
    - prometheus
    - alerts
    - records
    
- name: Restart and enable Prometheus
  systemd:
   name: prometheus
   enabled: yes
   state: restarted
   daemon_reload: true

- name: Update AlertManager Config
  template:
    src: "{{item}}.yml"
    dest: /opt/alertmanager/{{item}}.yml
  loop:
    - alertmanager

- name: Restart AlertManager Service
  systemd:
    name: alertmanager
    state: restarted
    enabled: yes   