- name: UPDATE | Copy prometheus.yaml to prometheus directory
  template:
   src: prometheus.yaml
   dest: /opt/prometheus/prometheus.yml

- name: Restart and enable Prometheus
  systemd:
   name: prometheus
   enabled: yes
   state: restarted