- name: Add Roboshop user
  ansible.builtin.user:
    name: roboshop
  register: ROBOSHOP_USER

- name: Download and unzip {{COMPONENT}} Archive
  ansible.builtin.unarchive:
    src: https://github.com/roboshop-devops-project/{{COMPONENT}}/archive/main.zip
    dest: /tmp
    remote_src: yes

- name: Remove old content from {{COMPONENT}} directory
  ansible.builtin.file:
    path: /home/roboshop/{{COMPONENT}}
    state: absent

- name: Copy extracted content to {{COMPONENT}} directory
  ansible.builtin.copy:
   src: /tmp/{{COMPONENT}}-main/
   dest: /home/roboshop/{{COMPONENT}}
   remote_src: yes
   owner: roboshop
   group: roboshop




