- name: Setup rsyslog
  template:
    src: rsyslog.conf
    dest: /etc/rsyslog.d/roboshop.conf

- name: Restart Rsyslog
  systemd:
    name: rsyslog
    state: restarted

- name: Install NodeJS, Make and GCC
  yum:
   name:
    - nodejs
    - make
    - gcc-c++
   state: present

- name: Include github download
  ansible.builtin.include_tasks: 
   file: download.yaml

- name: Install NodeJs dependencies
  community.general.npm:
    path: /home/roboshop/{{COMPONENT}}
  become_user: roboshop

- name: Include Systemd
  ansible.builtin.include_tasks: 
   file: systemd.yaml

- name: Include node_exporter
  ansible.builtin.include_tasks: 
   file: node_exporter.yaml

- name: Include Filebeat Setup Task
  ansible.builtin.include_tasks: 
   file: filebeat.yaml