- name: Copy Systemd service file of {{COMPONENT}} to setup service
  ansible.builtin.copy:
    src: systemd.service
    dest: /etc/systemd/system/{{COMPONENT}}.service

- name: Restart {{COMPONENT}} service
  systemd:
    name: "{{COMPONENT}}"
    state: restarted
    daemon_reload: true
    enabled: yes