route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 1m
  repeat_interval: 1m
  receiver: 'email'
receivers:
  - name: email
    email_configs:
      - to: mk.singh0246@gmail.com
        from: mk.singh0246@gmail.com
        smarthost: email-smtp.us-east-1.amazonaws.com:587
        auth_username: "{{SES_USER}}"
        auth_password: "{{SES_KEY}}"
        require_tls: yes
        send_resolved: true
inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']

