{
 "title": "All_In_One",
 "time": { "from": "now-1m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Active Services",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_systemd_unit_state{tagName=\"shipping\", state= \"active\", name= \"shipping.service\"}",
     "legendFormat": "{{tagName}}"
    },
    {
     "expr": "node_systemd_unit_state{tagName=\"frontend\", state= \"active\", name= \"nginx.service\"}",
     "legendFormat": "{{tagName}}"
    },
    {
     "expr": "node_systemd_unit_state{tagName=\"catalogue\", state= \"active\", name= \"catalogue.service\"}",
     "legendFormat": "{{tagName}}"
    },
    {
     "expr": "node_systemd_unit_state{tagName=\"user\", state= \"active\", name= \"user.service\"}",
     "legendFormat": "{{tagName}}"
    },
    {
     "expr": "node_systemd_unit_state{tagName=\"cart\", state= \"active\", name= \"cart.service\"}",
     "legendFormat": "{{tagName}}"
    },
    {
     "expr": "node_systemd_unit_state{tagName=\"payment\", state= \"active\", name= \"payment.service\"}",
     "legendFormat": "{{tagName}}"
    }
   ]
  },
  {
   "title": "CPU Usage %",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 16, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (rate(node_cpu_seconds_total{mode=\"idle\"}[5m]) * 100)",
     "legendFormat": "{{tagName}}"
    }
   ]
  },
  {
   "title": "Memory Usage %",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(node_memory_MemTotal_bytes-node_memory_MemAvailable_bytes) * 100 / node_memory_MemTotal_bytes",
     "legendFormat": "{{tagName}}"
    }
   ]
  }
 ]
}